version: '3'

services:

  postgres:
    image: 'postgres:alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: casa-do-codigo